export const color = {
  primaryForTop: '#004350',
  primary: '#00596B',
  primaryLow: '#F0F6F6',
  secondary: '#E8B000',
  secondaryLow: '#FFF6D9',
  white: '#fff',
  white87: 'rgba(255, 255, 255, 0.87)',
  white60: 'rgba(255, 255, 255, 0.60)',
  white40: 'rgba(255, 255, 255, 0.40)',
  black87: 'rgba(0, 0, 0, 0.87)',
  black60: 'rgba(0, 0, 0, 0.60)',
  black28: 'rgba(0, 0, 0, 0.28)',
  black20: 'rgba(0, 0, 0, 0.20)',
  black15: 'rgba(0, 0, 0, 0.15)',
  black10: 'rgba(0, 0, 0, 0.10)',
  primary2: '#B0CCD1',
  gray: '#f3f3f3',
  gray2: '#EDEDED',
  gray3: '#D5DCDD',
  red: '#a80000',
  redLow: '#F6E6E6',
};
export const routes = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  FORGOTPASSWORD: 'FORGOTPASSWORD',
  OTP: 'OTP',
  NEWPASSWORD: 'NEWPASSWORD',
  LOGINWITHNUMBER: 'LOGINWITHNUMBER',
  HOME: 'HOME',
  CONTACT: 'CONTACT',
  CHATS: 'CHATS',
  NEWCHAT: 'NEWCHAT',
  MESSAGE: 'MESSAGE',
  GROUP: 'GROUP',
  BOOKMARK: 'BOOKMARK',
  CHATPROFILE: 'CHATPROFILE',
  ADDMEMBERS: 'ADDMEMBERS',
  PROFILE: 'PROFILE',
  MARKATTENDENCE: 'MARKATTENDENCE',
  SCHEDULEFORM: 'SCHEDULEFORM',
  MEETING_HISTORY: 'MEETING_HISTORY',
  MEETING_DETAIL: 'MEETING_DETAIL',
  PROJECT_DETAIL: 'PROJECT_DETAIL',
  TICKET: 'TICKET',
  DISPATCHITEAM: 'DISPATCHITEAM',
  SCANPAGE: 'SCANPAGE',
  ORDERPAGE: 'ORDERPAGE',
  ADDTOINVENTORY: 'ADDTOINVENTORY',
  CHATEDIT: 'CHATEDIT',
  FORWARDMESSAGE: 'FORWARDMESSAGE',
  MESSAGEINFO: 'MESSAGEINFO',
  PENDINGATTENDANCE: 'PEMDINGATTENDANCE',
  TARGET_PROGRESS: 'TARGET_PROGRESS',
  MATERIAL_USED: 'MATERIAL_USED',
  SE_HOMEPAGE: 'SE_HOMEPAGE',
  PROJECT_SELECTION: 'PROJECT_SELECTION',
  SE_SUBTASK: 'SE_SUBTASK',
  ASSET_CART: 'ASSET_CART',
  WORKINSTRUCTION: 'WORKINSTRUCTION',
  CAMERA: 'CAMERA',
  PM_HOMEPAGE: 'PM_HOMEPAGE',
  PM_INVENTORY: 'PM_INVENTORY',
  CART_VIEW: 'CART_VIEW',
  PMSUBTASK_REVIEW: 'PMSUBTASK_REVIEW',
  PMPETTY_CASH: 'PMPETTY_CASH',
  PM_ORDERS: 'PM_ORDERS',
  PM_CONTRACTOR_1: 'PM_CONTRACTOR_1',
  PM_CONTRACTOR_2: 'PM_CONTRACTOR_2',
  PM_CONTRACTOR_3: 'PM_CONTRACTOR_3',
  PM_REQUESTS: 'PM_REQUESTS',
  PM_APPROVAL: 'PM_APPROVAL',
  MYBAG: 'MUBAG',
  ITEM_REQUEST: 'ITEM_REQUEST',
  ITEM_REQUEST_REVIEW: 'ITEM_REQUEST_REVIEW',
  MANPOWER_REQUEST: 'MANPOWER_REQUEST',
  PM_BAG: 'PM_BAG',
};

export const font = {
  NunitoBlack: 'Nunito-Black',
  NunitoBold: 'Nunito-Bold',
  NunitoExtraBold: 'Nunito-ExtraBold',
  NunitoExtraLight: 'Nunito-ExtraLight',
  NunitoLight: 'Nunito-Light',
  NunitoMedium: 'Nunito-Medium',
  NunitoRegular: 'Nunito-Regular',
  NunitoSemiBold: 'Nunito-SemiBold',
};
// export const apiUrl = "http://admin.suryacon.net/api/v1"
export const apiUrl = 'http://192.168.29.241:3000/api/v1';
export const ENDPOINT = 'http://192.168.29.174:8080';
// export const ENDPOINT = "http://socket.suryacon.net"
